// Auto-generated by: supabase gen types typescript --linked
// Run `pnpm supabase gen types typescript --linked > packages/db/types.ts` to regenerate
// Do not edit manually

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      // Generated types will appear here after running supabase gen types
    };
    Views: {};
    Functions: {};
    Enums: {
      round_status: 'open_submissions' | 'voting' | 'completed';
      league_playlist_mode: 'fresh' | 'cloned' | 'linked';
    };
    CompositeTypes: {};
  };
};
